-- JJ Signature public portal mode.
--
-- The current frontend uses a portal login rather than Supabase Auth. That
-- means auth.uid() is normally NULL, so admin-only RLS policies reject writes
-- even after the portal login succeeds. Apply this migration only when this
-- database is intentionally operated as a public/shared portal. It allows
-- anonymous visitors to read and manage operational records; do not use it
-- for a private multi-tenant application.

DO $$
DECLARE
  target text;
BEGIN
  FOREACH target IN ARRAY ARRAY[
    'categories', 'products', 'product_variants', 'coupons',
    'orders', 'order_items', 'advance_orders',
    'advance_order_timeline', 'advance_order_payments', 'store_settings',
    'expense_categories', 'expenses', 'stock_movements'
  ] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', target);
    EXECUTE format('DROP POLICY IF EXISTS public_portal_access ON public.%I', target);
    EXECUTE format(
      'CREATE POLICY public_portal_access ON public.%I FOR ALL TO anon, authenticated USING (true) WITH CHECK (true)',
      target
    );
  END LOOP;
END $$;

-- Remove the database-side admin gate for this explicitly public deployment.
-- This is intentionally insecure for private or multi-tenant deployments.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$ SELECT true; $$;

-- The frontend calls these SECURITY DEFINER workflows without a Supabase
-- session. Table policies do not grant RPC execution, so grant the exact
-- signatures used by the application as well.
GRANT EXECUTE ON FUNCTION public.adjust_product_stock(BIGINT, NUMERIC, TEXT, TEXT) TO anon, authenticated;

-- Allow BIGSERIAL coupon IDs to be generated by anonymous inserts.
GRANT USAGE, SELECT ON SEQUENCE public.coupons_id_seq TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
